### ISSUE TITLE
Failing to start (because import)

### ISSUE THREAD

**Issue by Nex-Coder** [SaifAqqad/corsair_battery_level#3]
Hi, I'm not really a node.js kinda guy but i do have it setup with npm on my system. However, i get this error when trying to run the app with node.
```
index.js:1
(function (exports, require, module, __filename, __dirname) { import { NotifyIcon, Icon, Menu } from "not-the-systray";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

running app.vbs doesn't do anything either it seems.
Any clues if its an issue on my end? Maybe a version mismatch.

**Comment by SaifAqqad** [comment]
How are you running it? and what version of node are you running it with?

**Comment by Nex-Coder** [comment]
Yeah, nevermind. I was running an insanely old version of node. updated to 16.X and its working now. Thanks for this project btw <3
